#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: Visual Studio 2019

environment:
  GITHUB_REPO_TOKEN:
    secure: qJEufJv866eebR/Boe1UnV3p1arOIX9BTyqAQnAVY49h4Ks40Sr0rHb3iN70e7BZ
  GITHUB_EMAIL:
    secure: Z6F+xZzdZzc5DMYB/4J0KUhyoTzTlXH75ciGl7hFH9s=
  APPVEYOR_RDP_PASSWORD:
    secure: IvxSZoWD+DpqNjUP7mFjPA==

branches:
  # blacklist
  except:
    - gh-pages

build: off

clone_script:
  - cmd: |
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%

init:
  - ps: |
      $ErrorActionPreference = "Stop"
#     IEX ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: npm install

build_script:
  - cmd: npm run build

on_finish:
  - ps: |
#     $blockRdp = $true; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

for:
  -
    branches:
      only:
        - master

    deploy_script:
      - ps: |
          if ($Env:APPVEYOR_REPO_TAG_NAME -eq "deploy") {
            Start-Process git -ArgumentList "config --global credential.helper store" -NoNewWindow -Wait
            Add-Content (Join-Path $Env:USERPROFILE ".git-credentials") "https://$($Env:GITHUB_REPO_TOKEN):x-oauth-basic@github.com/sholtee/cv.git"
            Start-Process git -ArgumentList "config --global user.email $($Env:GITHUB_EMAIL)" -NoNewWindow -Wait
            Start-Process git -ArgumentList "config --global user.name [Bot]" -NoNewWindow -Wait

            Move-Item .\dist -Destination $Env:TEMP
            Start-Process git -ArgumentList "reset --hard" -NoNewWindow -Wait
            Start-Process git -ArgumentList "switch gh-pages" -NoNewWindow -Wait
            Get-ChildItem -Path . -Exclude .git | Remove-Item -Recurse -Force
            Move-Item $Env:TEMP\dist\* -Destination .
            Start-Process git -ArgumentList "add --all" -NoNewWindow -Wait
            Start-Process git -ArgumentList "commit -m deploy" -NoNewWindow -Wait
            Start-Process git -ArgumentList "push origin gh-pages" -NoNewWindow -Wait
          }
